#!/bin/sh
# config nuclei xec disable autoneg, setting 100M, fduplex mode.

start() {
	ethtool -s eth0 autoneg off speed 100 duplex full
	ifconfig lo up
	udhcpc
}

case "$1" in
  start|stop|restart)
	"$1";;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac
