variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GET_SOURCES_ATTEMPTS: 5
    GIT_STRATEGY: fetch
    FF_USE_FASTZIP: "true"

before_script:
    - source /home/share/devtools/env.sh

stages:
    - build_ux600
    - build_ux600fd
    - run_ux600
    - run_ux600fd

cache:
    paths:
        - buildroot/dl

## Job template for build linux sdk
.build_linux_sdk_template: &build_linux_sdk_job_def
    interruptible: true
    only:
        changes:
          - conf/*
          - Makefile
          - .gitlab-ci.yml
          - buildroot
          - freeloader
          - linux
          - u-boot
    artifacts:
        name: "bootimages-${SOC}-${CORE}-${BOOT_MODE}-${CI_COMMIT_SHA::8}"
        paths:
            - work/${SOC}/
            - build_*.log.*
        expire_in: 2 day
    tags:
        - env::native
        - host::xls01
    script:
        - echo ">>Clean previous build workspace"
        - make clean
        - echo ">>Show help message for $SOC - $CORE - $BOOT_MODE"
        - make help
        - echo ">>Build buildroot_initramfs_sysroot for $CORE"
        - |
            make -j buildroot_initramfs_sysroot > >(tee build_sysroot.log |grep '>>>') || {
                echo 'Show last 200 lines of build log'
                tail -n 200 build_sysroot.log
                xz -f -z build_sysroot.log
                exit 1
            }
        - xz -f -z build_sysroot.log
        - echo ">>Build multiple CPU_HZ freeloader for $SOC - $CORE - $BOOT_MODE"
        - |
            export MAKEOPTS="SOC=$SOC CORE=$CORE BOOT_MODE=${BOOT_MODE}"
            export SELVAR="CPU_HZ"
            export VARLIST="16000000,100000000"
            bash .github/build_multiple_freeloader.sh > >(tee build_cpuhz_freeloader.log) || {
                xz -f -z build_cpuhz_freeloader.log
                exit 1
            }
            unset MAKEOPTS SELVAR VARLIST
        - xz -f -z build_cpuhz_freeloader.log
        - echo ">>Build simulation freeloader for $SOC - $CORE - $BOOT_MODE"
        - |
            export MAKEOPTS="SOC=$SOC CORE=$CORE BOOT_MODE=${BOOT_MODE}"
            export SELVAR="SIMULATION"
            export VARLIST="1"
            bash .github/build_multiple_freeloader.sh > >(tee build_simu_freeloader.log) || {
                xz -f -z build_simu_freeloader.log
                exit 1
            }
            unset MAKEOPTS SELVAR VARLIST
        - xz -f -z build_simu_freeloader.log
        - echo ">>Build freeloader for $SOC - $CORE - $BOOT_MODE"
        - |
            echo ">>>Build freeloader for default MHz"
            make freeloader > >(tee build_freeloader.log) || {
                xz -f -z build_freeloader.log
                exit 1
            }
        - xz -f -z build_freeloader.log
        - echo ">>Build and generate boot images for $SOC - $CORE - $BOOT_MODE"
        - |
            make preboot && make -j bootimages > >(tee build_bootimages.log) || {
                xz -f -z build_bootimages.log
                exit 1
            }
        - xz -f -z build_bootimages.log
        - |
            echo ">>Build and generate qemu images for $SOC - $CORE - $BOOT_MODE"
            echo ">>> Apply workaround: change TIMERCLK_FREQ from 32768 to 1000000"
            #sed -i "s/32768/1000000/" conf/$SOC/*.dts
            export TIMER_HZ=1000000
            make freeloader
            QEMU_FREELOADER=work/$SOC/freeloader_qemu.elf
            cp work/$SOC/freeloader/freeloader.elf $QEMU_FREELOADER
            make -j DISK_SIZE=128 gendisk > >(tee build_qemu_disk.log) || {
                xz -f -z build_qemu_disk.log
                exit 1
            }
            echo ">>> Reset workaround and source code, and rebuilt freeloader and boot images"
            git reset --hard
            make genboot
            xz -f -z build_qemu_disk.log
            unset TIMER_HZ
        - |
            RUNQEMUSH=work/$SOC/run_qemu.sh
            echo "qemu-system-riscv64 -M nuclei_u,download=flashxip -cpu nuclei-ux900fd,ext=$ARCH_EXT -smp 8 -m 256M -bios freeloader_qemu.elf -nographic -drive file=disk.img,if=sd,format=raw" > $RUNQEMUSH
            chmod +x $RUNQEMUSH
        - |
            if [ "x$SOC" == "xdemosoc" ] ; then
                echo ">>Will build xlspike simulation images only for demosoc"
                echo ">>Build simulation target for $SOC - $CORE - $BOOT_MODE"
                make presim && make -j opensbi_sim > >(tee build_opensbi_payload.log) || {
                    xz -f -z build_opensbi_payload.log
                    exit 1
                }
                cp -f work/${SOC}/opensbi/platform/nuclei/${SOC}/firmware/fw_payload.elf work/${SOC}/fw_payload_xlspike.elf
                xz -f -z build_opensbi_payload.log
            fi
        - |
            genbootzip=work/${SOC}/genboot_artifacts_${CI_COMMIT_SHA::8}.zip
            echo "Zip all generated boot images and freeloader elfs to ${genbootzip}"
            rm -f ${genbootzip}
            zip -r ${genbootzip} work/${SOC}/boot.zip work/${SOC}/freeloader/freeloader.elf work/${SOC}/run_qemu.sh work/${SOC}/disk.img work/${SOC}/freeloader_*.elf work/${SOC}/buildstamp.txt work/${SOC}/fw_payload_xlspike.elf

## Job template for run linux in xlspike
.run_linux_sdk_xlspike_template: &run_linux_sdk_xlspike_job_def
    interruptible: true
    only:
        changes:
          - conf/*
          - Makefile
          - .gitlab-ci.yml
          - buildroot
          - freeloader
          - linux
          - u-boot
    tags:
        - env::native
        - host::xls01
    script:
        - |
            if [ "x$SOC" != "xdemosoc" ] ; then
                echo ">>Will not run xlspike simulation for $SOC"
                exit 0
            fi
            timeout --foreground -s SIGKILL 12m xl_spike work/${SOC}/fw_payload_xlspike.elf > >(tee run_xlspike.log) || {
                if cat run_xlspike.log | grep "Run /init" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
                if cat run_xlspike.log | grep "Welcome to" ; then echo "Pass simulation" && exit 0; else echo "Failed init process" && exit 1; fi;
            }

## Job template for run linux in qemu
.run_linux_sdk_qemu_template: &run_linux_sdk_qemu_job_def
    interruptible: true
    only:
        changes:
          - conf/*
          - Makefile
          - .gitlab-ci.yml
          - buildroot
          - freeloader
          - linux
          - u-boot
    tags:
        - env::native
        - host::xls01
    script:
        - echo ">>Run using qemu for $SOC - $CORE - $BOOT_MODE"
        - |
            if [ "x$SOC" != "xdemosoc" ] ; then
                echo ">>Will not run qemu simulation for $SOC"
                exit 0
            fi
            cd work/$SOC
            # $(cat run_qemu.sh) is workaround for directly run bash run_qemu.sh
            # If do kill it will just kill bash process, the qemu process is not killed
            # SIGTERM is better for kill qemu
            timeout --foreground -s SIGTERM 4m $(cat run_qemu.sh) > >(tee run_qemu.log) || {
                if cat run_qemu.log | grep "Run /init" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
                if cat run_qemu.log | grep "Welcome to" ; then echo "Pass simulation" && exit 0; else echo "Failed init process" && exit 1; fi;
            }

## Job for build sdk
# Build For UX600 Core, without FPU, flash boot mode
build_ux600_flash:
    stage: build_ux600
    variables:
        SOC: "demosoc"
        CORE: "ux600"
        ARCH_EXT: ""
        BOOT_MODE: "flash"
    parallel:
        matrix:
            - SOC: ["demosoc", "evalsoc"]
    <<: *build_linux_sdk_job_def

## Job for build sdk
# Build For UX600 Core, without FPU, sd boot mode
build_ux600_sd:
    stage: build_ux600
    variables:
        SOC: "demosoc"
        CORE: "ux600"
        ARCH_EXT: ""
        BOOT_MODE: "sd"
    parallel:
        matrix:
            - SOC: ["demosoc", "evalsoc"]
    <<: *build_linux_sdk_job_def

# Manual job for ux600 sd
build_ux600_sd_manual:
    interruptible: true
    stage: build_ux600
    when: manual
    needs:
        - job: build_ux600_sd
    variables:
        SOC: "demosoc"
        CORE: "ux600"
        ARCH_EXT: ""
        BOOT_MODE: "sd"
    only:
        changes:
          - conf/*
          - Makefile
          - .gitlab-ci.yml
          - buildroot
          - freeloader
          - linux
          - u-boot
    artifacts:
        name: "bootimages-${SOC}-${CORE}-${BOOT_MODE}-${CI_COMMIT_SHA::8}"
        paths:
            - work/${SOC}/freeloader/freeloader.elf
            - work/${SOC}/boot.zip
        expire_in: 2 day
    tags:
        - env::native
        - host::xls01
    script:
        - make preboot
        - make freeloader
        - make bootimages

# Manual job for ux600 flash
build_ux600_flash_manual:
    interruptible: true
    stage: build_ux600
    when: manual
    needs:
        - job: build_ux600_flash
    variables:
        SOC: "demosoc"
        CORE: "ux600"
        ARCH_EXT: ""
        BOOT_MODE: "flash"
    only:
        changes:
          - conf/*
          - Makefile
          - .gitlab-ci.yml
          - buildroot
          - freeloader
          - linux
          - u-boot
    artifacts:
        name: "bootimages-${SOC}-${CORE}-${BOOT_MODE}-${CI_COMMIT_SHA::8}"
        paths:
            - work/${SOC}/freeloader/freeloader.elf
            - work/${SOC}/boot.zip
        expire_in: 2 day
    tags:
        - env::native
        - host::xls01
    script:
        - make preboot
        - make freeloader
        - make bootimages

release_sources:
    interruptible: true
    stage: build_ux600
    needs:
        - job: build_ux600_flash
    tags:
        - env::native
        - host::xls01
    script:
        - activate_swdev
        - make snapshot
        - snapshot_zip=($(ls -t1 GENERATED/snapshot/snapshot_*.zip))
        - cp -f ${snapshot_zip} linuxsdk_${CI_COMMIT_REF_NAME//\//\_}_${CI_COMMIT_SHA::8}.zip
    artifacts:
        name: "nuclei_linuxsdk-job${CI_JOB_ID}_${CI_COMMIT_SHA::8}"
        paths:
            - buildroot/dl
            - linuxsdk_*.zip
        expire_in: 2 day

## Job for run sim
# Run For UX600 Core, without FPU, flash boot mode
run_ux600_flash_xlspike:
    stage: run_ux600
    dependencies:
        - build_ux600_flash
    variables:
        SOC: "demosoc"
        CORE: "ux600"
        BOOT_MODE: "flash"
    <<: *run_linux_sdk_xlspike_job_def

## Job for run sim
# Run For UX600 Core, without FPU, sd boot mode
run_ux600_sd_xlspike:
    stage: run_ux600
    dependencies:
        - build_ux600_sd
    variables:
        SOC: "demosoc"
        CORE: "ux600"
        BOOT_MODE: "sd"
    <<: *run_linux_sdk_xlspike_job_def

## Job for run qemu
# Run For UX600 Core, without FPU, flash boot mode
run_ux600_flash_qemu:
    stage: run_ux600
    dependencies:
        - build_ux600_flash
    variables:
        SOC: "demosoc"
        CORE: "ux600"
        BOOT_MODE: "flash"
    <<: *run_linux_sdk_qemu_job_def

## Job for run qemu
# Run For UX600 Core, without FPU, sd boot mode
run_ux600_sd_qemu:
    stage: run_ux600
    dependencies:
        - build_ux600_sd
    variables:
        SOC: "demosoc"
        CORE: "ux600"
        BOOT_MODE: "sd"
    <<: *run_linux_sdk_qemu_job_def

## Job for build sdk
# Build For UX600FD Core, with FPU, flash boot mode
build_ux600fd_flash:
    stage: build_ux600fd
    dependencies:
    variables:
        SOC: "demosoc"
        CORE: "ux600fd"
        ARCH_EXT: ""
        BOOT_MODE: "flash"
    parallel:
        matrix:
            - SOC: ["demosoc", "evalsoc"]
    <<: *build_linux_sdk_job_def

## Job for build sdk
# Build For UX600FD Core, with FPU, sd boot mode
build_ux600fd_sd:
    stage: build_ux600fd
    dependencies:
    variables:
        SOC: "demosoc"
        CORE: "ux600fd"
        ARCH_EXT: ""
        BOOT_MODE: "sd"
    parallel:
        matrix:
            - SOC: ["demosoc", "evalsoc"]
    <<: *build_linux_sdk_job_def

# Manual job for ux600fd sd
build_ux600fd_sd_manual:
    interruptible: true
    stage: build_ux600fd
    when: manual
    needs:
        - job: build_ux600fd_sd
    variables:
        SOC: "demosoc"
        CORE: "ux600fd"
        ARCH_EXT: ""
        BOOT_MODE: "sd"
    only:
        changes:
          - conf/*
          - Makefile
          - .gitlab-ci.yml
          - buildroot
          - freeloader
          - linux
          - u-boot
    artifacts:
        name: "bootimages-${SOC}-${CORE}-${BOOT_MODE}-${CI_COMMIT_SHA::8}"
        paths:
            - work/${SOC}/freeloader/freeloader.elf
            - work/${SOC}/boot.zip
        expire_in: 2 day
    tags:
        - env::native
        - host::xls01
    script:
        - make preboot
        - make freeloader
        - make bootimages

# Manual job for ux600fd flash
build_ux600fd_flash_manual:
    interruptible: true
    stage: build_ux600fd
    when: manual
    needs:
        - job: build_ux600fd_flash
    variables:
        SOC: "demosoc"
        CORE: "ux600fd"
        ARCH_EXT: ""
        BOOT_MODE: "flash"
    only:
        changes:
          - conf/*
          - Makefile
          - .gitlab-ci.yml
          - buildroot
          - freeloader
          - linux
          - u-boot
    artifacts:
        name: "bootimages-${SOC}-${CORE}-${BOOT_MODE}-${CI_COMMIT_SHA::8}"
        paths:
            - work/${SOC}/freeloader/freeloader.elf
            - work/${SOC}/boot.zip
        expire_in: 2 day
    tags:
        - env::native
        - host::xls01
    script:
        - make preboot
        - make freeloader
        - make bootimages

## Job for run sim
# Run For UX600FD Core, with FPU, flash boot mode
# This ux600fd init process will fail
run_ux600fd_flash_xlspike:
    stage: run_ux600fd
    allow_failure: true
    dependencies:
        - build_ux600fd_flash
    variables:
        SOC: "demosoc"
        CORE: "ux600fd"
        BOOT_MODE: "flash"
    <<: *run_linux_sdk_xlspike_job_def

## Job for run sim
# Run For UX600FD Core, with FPU, sd boot mode
# This ux600fd init process will fail
run_ux600fd_sd_xlspike:
    stage: run_ux600fd
    allow_failure: true
    dependencies:
        - build_ux600fd_sd
    variables:
        SOC: "demosoc"
        CORE: "ux600fd"
        BOOT_MODE: "sd"
    <<: *run_linux_sdk_xlspike_job_def

## Job for run qemu
# Run For UX600FD Core, with FPU, flash boot mode
# This ux600fd init process will fail
run_ux600fd_flash_qemu:
    stage: run_ux600fd
    allow_failure: true
    dependencies:
        - build_ux600fd_flash
    variables:
        SOC: "demosoc"
        CORE: "ux600fd"
        BOOT_MODE: "flash"
    <<: *run_linux_sdk_qemu_job_def

## Job for run qemu
# Run For UX600FD Core, with FPU, sd boot mode
# This ux600fd init process will fail
run_ux600fd_sd_qemu:
    stage: run_ux600fd
    allow_failure: true
    dependencies:
        - build_ux600fd_sd
    variables:
        SOC: "demosoc"
        CORE: "ux600fd"
        BOOT_MODE: "sd"
    <<: *run_linux_sdk_qemu_job_def
