#!/bin/sh
# config nuclei xec autoneg on for NUCLEI P0 SOC

ls /sys/class/net/eth0 2>1 > /dev/null
haseth0=$?

ls /sys/class/net/eth1 2>1 > /dev/null
haseth1=$?

start() {
	ifconfig lo up &
	if [[ $haseth0 == 0 ]] then
		echo "Configure eth0!"
		#udhcpc -i eth0 -b -R -o -O 1 -O 6 -O 15 &
		udhcpc -i eth0 -b -R &
	fi
	if [[ $haseth1 == 0 ]] then
		echo "Configure eth1!"
		udhcpc -i eth1 -b -R &
	fi
}

stop() {
	ifconfig lo down &
	if [[ $haseth0 == 0 ]] then
		echo "eth0 down!"
		ifconfig eth0 down &
	fi
	if [[ $haseth1 == 0 ]] then
		echo "eth1 down!"
		ifconfig eth1 down &
	fi
}

restart() {
	start
}

case "$1" in
  start|stop|restart)
	"$1";;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
