name: Build Linux SDK Docker Image

on:
  push:
    branches: [ dev_nuclei_next ]
    paths-ignore:
    - README.md
    - LICENSE
    - .gitlab-ci.yml
    - .gitignore
  pull_request:
    branches: [ dev_nuclei_next ]

jobs:

  # This workflow contains a single job called "build"
  build:
    name: build docker image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Linux SDK Code
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Build Docker Image
        run: |
          cd .github
          docker build . -f linuxsdk.Dockerfile -t linuxsdk:latest
          docker images

      - name: Test Docker Image
        run: |
          docker run -i linuxsdk:latest bash run_qemu.sh

      - name: Publish Docker Image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Login to docker hub"
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }} docker.io
          DOCKER_REPO=docker.io/nucleisoftware/linuxsdk
          docker tag linuxsdk:latest ${DOCKER_REPO}:ci
          docker push ${DOCKER_REPO}:ci
          echo "Docker image is pushed to https://hub.docker.com/repository/docker/nucleisoftware/linuxsdk"
