name: Build Linux SDK Docker Image

on:
  push:
    branches: [ dev*, feature/* ]
    paths-ignore:
    - README.md
    - LICENSE
    - .gitlab-ci.yml
    - .gitignore
  pull_request:
    branches: [ dev_nuclei_next ]

jobs:

  # This workflow contains a single job called "build"
  build:
    name: build docker image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Linux SDK Code
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Build Docker Image
        run: |
          cd .github
          docker build . -f linuxsdk.Dockerfile -t linuxsdk:latest


